development:
  adapter: postgresql
  encoding: unicode
  database: triage_web_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: triage_web_test
  pool: 5
  username: postgres
  password:
